import { DWDimensionApiGetWikisResponse } from '../api/dw_dimensions_api_interface';

export const fakeWikiListResponse: DWDimensionApiGetWikisResponse = [
  {
    wiki_id: '1',
    dbname: 'bahrain',
    sitename: 'bahrain',
    url: 'http://bahrain.fandom.com/',
    domain: 'bahrain.fandom.com',
    title: 'Bahrain',
    founding_user_id: '0',
    public: '1',
    lang: 'en',
    lang_id: '75',
    vertical_id: '5',
    vertical_name: 'Lifestyle',
    cluster: 'c1',
    created_at: '2004-11-11 23:33:14',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
  {
    wiki_id: '2',
    dbname: 'calgary',
    sitename: 'calgary',
    url: 'http://calgary.fandom.com/',
    domain: 'calgary.fandom.com',
    title: 'Calgary Wiki',
    founding_user_id: '0',
    public: '1',
    lang: 'en',
    lang_id: '75',
    vertical_id: '5',
    vertical_name: 'Lifestyle',
    cluster: 'c1',
    created_at: '2004-11-11 23:33:14',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
  {
    wiki_id: '3',
    dbname: 'languagewikisindex',
    sitename: 'wikicities',
    url: 'http://languagewikisindex.fandom.com/',
    domain: 'languagewikisindex.fandom.com',
    title: 'Language Wikis Index Wiki',
    founding_user_id: '4807560',
    public: '1',
    lang: 'en',
    lang_id: '75',
    vertical_id: '5',
    vertical_name: 'Lifestyle',
    cluster: 'c7',
    created_at: '2018-10-30 11:12:28',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
  {
    wiki_id: '6',
    dbname: 'gknowledge',
    sitename: 'gknowledge',
    url: 'http://gknowledge.fandom.com/',
    domain: 'gknowledge.fandom.com',
    title: 'G. Knowledge',
    founding_user_id: '0',
    public: '1',
    lang: 'en',
    lang_id: '75',
    vertical_id: '5',
    vertical_name: 'Lifestyle',
    cluster: 'c1',
    created_at: '2004-11-11 23:36:39',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
  {
    wiki_id: '7',
    dbname: 'inteq',
    sitename: 'inteq',
    url: 'http://inteq.fandom.com/',
    domain: 'inteq.fandom.com',
    title: 'INTEQ KB',
    founding_user_id: '0',
    public: '1',
    lang: 'pt',
    lang_id: '244',
    vertical_id: '5',
    vertical_name: 'Lifestyle',
    cluster: 'c1',
    created_at: '2004-11-11 23:33:14',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
  {
    wiki_id: '8',
    dbname: 'peace',
    sitename: 'peace',
    url: 'http://peace.fandom.com/',
    domain: 'peace.fandom.com',
    title: 'Peace Elements',
    founding_user_id: '0',
    public: '1',
    lang: 'en',
    lang_id: '75',
    vertical_id: '5',
    vertical_name: 'Lifestyle',
    cluster: 'c1',
    created_at: '2004-11-11 23:33:14',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
  {
    wiki_id: '10',
    dbname: 'sca21',
    sitename: 'sca21',
    url: 'http://sca21.fandom.com/',
    domain: 'sca21.fandom.com',
    title: 'Sustainable Community Action',
    founding_user_id: '55',
    public: '1',
    lang: 'en',
    lang_id: '75',
    vertical_id: '5',
    vertical_name: 'Lifestyle',
    cluster: 'c1',
    created_at: '2004-11-11 23:33:14',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
  {
    wiki_id: '13',
    dbname: 'tokipona',
    sitename: 'tokipona',
    url: 'http://tokipona.fandom.com/',
    domain: 'tokipona.fandom.com',
    title: 'Wikipesija',
    founding_user_id: '5114',
    public: '1',
    lang: 'en',
    lang_id: '75',
    vertical_id: '5',
    vertical_name: 'Lifestyle',
    cluster: 'c1',
    created_at: '2004-04-04 01:33:33',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
  {
    wiki_id: '15',
    dbname: 'UniversityWikiNodeWiki',
    sitename: 'UniversityWikiNodeWiki',
    url: 'http://universitywikinodewiki.fandom.com/',
    domain: 'universitywikinodewiki.fandom.com',
    title: 'The University Wiki Node Wiki',
    founding_user_id: '0',
    public: '1',
    lang: 'en',
    lang_id: '75',
    vertical_id: '5',
    vertical_name: 'Lifestyle',
    cluster: 'c1',
    created_at: '2004-11-05 18:27:17',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
  {
    wiki_id: '18',
    dbname: 'zhwikimac',
    sitename: 'zh.mac',
    url: 'http://mac.fandom.com/zh/',
    domain: 'mac.fandom.com/zh',
    title: '维基麦',
    founding_user_id: '10',
    public: '1',
    lang: 'zh',
    lang_id: '345',
    vertical_id: '5',
    vertical_name: 'Lifestyle',
    cluster: 'c1',
    created_at: '2004-11-11 15:01:40',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
  {
    wiki_id: '19',
    dbname: 'guilds',
    sitename: 'guilds',
    url: 'http://neopets.fandom.com/',
    domain: 'neopets.fandom.com',
    title: 'Neopets Wiki',
    founding_user_id: '0',
    public: '1',
    lang: 'en',
    lang_id: '75',
    vertical_id: '2',
    vertical_name: 'Games',
    cluster: 'c1',
    created_at: '2004-12-18 07:03:14',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
  {
    wiki_id: '20',
    dbname: 'religionwiki',
    sitename: 'religion',
    url: 'http://religion.wikia.org/',
    domain: 'religion.wikia.org',
    title: 'Religion-wiki',
    founding_user_id: '1961',
    public: '1',
    lang: 'en',
    lang_id: '75',
    vertical_id: '5',
    vertical_name: 'Lifestyle',
    cluster: 'c1',
    created_at: '2004-08-11 14:17:31',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
  {
    wiki_id: '21',
    dbname: 'townntitles',
    sitename: 'ru.townn-titles',
    url: 'http://townn-titles.fandom.com/ru/',
    domain: 'townn-titles.fandom.com/ru',
    title: 'Нижегородский топонимический словарь',
    founding_user_id: '0',
    public: '1',
    lang: 'ru',
    lang_id: '254',
    vertical_id: '5',
    vertical_name: 'Lifestyle',
    cluster: 'c1',
    created_at: '2004-12-16 09:17:43',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
  {
    wiki_id: '23',
    dbname: 'flink',
    sitename: 'flink',
    url: 'http://flink.fandom.com/',
    domain: 'flink.fandom.com',
    title: 'no',
    founding_user_id: '0',
    public: '1',
    lang: 'no',
    lang_id: '219',
    vertical_id: '5',
    vertical_name: 'Lifestyle',
    cluster: 'c1',
    created_at: '2004-12-21 07:18:00',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
  {
    wiki_id: '24',
    dbname: 'lasvegas',
    sitename: 'lasvegas',
    url: 'http://lasvegas.wikia.org/',
    domain: 'lasvegas.wikia.org',
    title: 'Las Vegas',
    founding_user_id: '0',
    public: '1',
    lang: 'en',
    lang_id: '75',
    vertical_id: '5',
    vertical_name: 'Lifestyle',
    cluster: 'c1',
    created_at: '2004-12-21 05:40:56',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
  {
    wiki_id: '25',
    dbname: 'babylon5',
    sitename: 'babylon5',
    url: 'http://babylon5.fandom.com/',
    domain: 'babylon5.fandom.com',
    title: 'The Babylon Project',
    founding_user_id: '0',
    public: '1',
    lang: 'en',
    lang_id: '75',
    vertical_id: '1',
    vertical_name: 'TV',
    cluster: 'c1',
    created_at: '2004-12-21 13:30:25',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: '4079189',
  },
  {
    wiki_id: '26',
    dbname: 'gwguild',
    sitename: 'wesleyan',
    url: 'http://guildwars.fandom.com/',
    domain: 'guildwars.fandom.com',
    title: 'GuildWars Wiki',
    founding_user_id: '686174',
    public: '1',
    lang: 'en',
    lang_id: '75',
    vertical_id: '2',
    vertical_name: 'Games',
    cluster: 'c1',
    created_at: '2001-01-15 00:00:00',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
  {
    wiki_id: '28',
    dbname: 'abitur',
    sitename: 'abitur',
    url: 'http://abitur.fandom.com/de/',
    domain: 'abitur.fandom.com/de',
    title: 'Abitur Wiki',
    founding_user_id: '114',
    public: '0',
    lang: 'de',
    lang_id: '62',
    vertical_id: '5',
    vertical_name: 'Lifestyle',
    cluster: 'c1',
    created_at: '2004-12-24 10:16:26',
    deleted: '1',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
  {
    wiki_id: '29',
    dbname: 'Intuite',
    sitename: 'Intuite',
    url: 'http://intuite.fandom.com/',
    domain: 'intuite.fandom.com',
    title: 'la Tour Sombre',
    founding_user_id: '111',
    public: '1',
    lang: 'fr',
    lang_id: '88',
    vertical_id: '5',
    vertical_name: 'Lifestyle',
    cluster: 'c1',
    created_at: '2004-11-11 23:33:14',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
  {
    wiki_id: '30',
    dbname: 'delphi',
    sitename: 'delphi',
    url: 'http://delphi.fandom.com/',
    domain: 'delphi.fandom.com',
    title: 'Delphi Programming',
    founding_user_id: '92',
    public: '1',
    lang: 'en',
    lang_id: '75',
    vertical_id: '5',
    vertical_name: 'Lifestyle',
    cluster: 'c1',
    created_at: '2004-11-11 23:33:14',
    deleted: '0',
    is_test_wiki: '0',
    fc_community_id: null,
    is_kid_wiki: '0',
    wiki_manager: null,
  },
];
